# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://indexer.housefire.tududes.com"
rpc_url = "https://rpc.housefire.tududes.com"
masp_indexer_url = "https://masp.housefire.tududes.com"
#localnet_enabled = false
#fathom_site_id = ""
