# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://namada-housefire-idx.emberstake.xyz"
rpc_url = "https://rpc.housefire.tududes.com"
masp_indexer_url = "https://namada-housefire-masp-idx.emberstake.xyz"
localnet_enabled = false
